{% set version = "2.6.0" %}

package:
  name: keras
  version: {{ version }}

source:
  git_url: https://github.com/keras-team/keras
  git_rev: v{{ version }}
  patches:
    - 0001-Updated-protobuf-to-3.14.patch     #[protobuf == "3.14.*"] 
build:
  number: 1
  string: h{{ PKG_HASH }}_{{ build_type }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: h{{ PKG_HASH }}_{{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
{% if build_type == 'cuda' %}
  script_env:
    - CUDA_HOME
{% endif %}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    # conda build requirements
    - git >=2.2
    - bazel {{ bazel }}
    - pip
    - python {{ python }}
    - tensorflow-base {{ tensorflow }}
  run:
    - pandas
    - pydot   #[py<39]
    - scipy {{ scipy }}
    - tensorflow-base {{ tensorflow }}
    - portpicker
    - python {{ python }}
    - pyyaml {{ pyyaml }}
    - pillow {{ pillow }}

test:
  imports:
    - keras
    - keras.backend
    - keras.datasets
    - keras.engine
    - keras.layers
    - keras.preprocessing
    - keras.utils
    - keras.wrappers

about:
  home: https://github.com/keras-team/keras
  license: MIT
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

